name: SimpleRTA
description: A simple plugin about RTA Game
main: cn.widecss.SimpleRTAPlugin
version: 0.8
api-version: 1.16

authors:
  - Widecss

commands:
  rta:
    description: A command from SimpleRTA plugin

#softdepend:
#  - ProtocolSupport

permissions:
  simplertp.admin:
    description: Permission to use the admin command
#  skins.*:
#    description: All permissions combined
#    children:
#      skins.menu: true
#      skins.info: true
#      skins.reload: true